package net.frontlinesms.settings;

public enum CoreSettingsSections {
		APPEARANCE,
		GENERAL,
		GENERAL_DATABASE,
		GENERAL_EMAIL,
		SERVICES,
		SERVICES_DEVICES,
		SERVICES_DEVICE,
		SERVICES_INTERNET_SERVICES,
		SERVICES_MMS
}
